### ISSUE TITLE
Git: NPE on getting the commits

### ISSUE THREAD

**Issue by dcoraboeuf** [dcoraboeuf/ontrack#196]
Seen on Cloudbees:

```
java.lang.NullPointerException
    at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
    at org.eclipse.jgit.revwalk.RevWalk.lookupCommit(RevWalk.java:634)
    at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:297)
    at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:172)
    at net.ontrack.extension.git.client.impl.DefaultGitRepository.getCommitForTag(DefaultGitRepository.java:90)
```

**Comment by dcoraboeuf** [comment]
The tags are in the form `ontrack-1.*` but the builds were imported as `1.*`. Reimporting the build numbers using the regex `(ontrack-1\.\d+)` solves the issue.
