### ISSUE TITLE
NullPointerException for changelog of github project without API key define.

### ISSUE THREAD

**Issue by flesire** [dcoraboeuf/ontrack#243]

**Comment by dcoraboeuf** [comment]
1. I create a new `ontrack` project
2. I define only the `GitHub project` property (to `dcoraboeuf/ontrack`)
3. I create the 1.x branch (with no parameter - `master` is the default)
4. I import the builds (no parameter)
5. I select a change log

... and get no NPE...

Can you test the scenario above or tell me the differences with what you have? And attach any stack trace you find.

FYI, the code that relies on the API token is at `net.ontrack.extension.github.client.DefaultGitHubClientConfiguratorFactory`.

The API token is needed only if you know you will have many many accesses to the change log.

**Comment by flesire** [comment]
```
java.lang.NullPointerException
    at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
    at org.eclipse.jgit.revwalk.RevWalk.lookupCommit(RevWalk.java:634)
    at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:297)
    at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:172)
    at net.ontrack.extension.git.client.impl.DefaultGitRepository.getCommitForTag(DefaultGitRepository.java:90)
    at net.ontrack.extension.git.client.impl.DefaultGitClient.log(DefaultGitClient.java:97)
```

**Comment by dcoraboeuf** [comment]
Code corrected by #245. Can you check the ticket again since I could not reproduce it in the first place?
