### ISSUE TITLE
NPE on ontrack@ontrack when accessing a change log

### ISSUE THREAD

**Issue by dcoraboeuf** [dcoraboeuf/ontrack#249]
When accessing the change log between 1.36 & 1.38:

```
java.lang.NullPointerException
    at net.ontrack.extension.github.client.DefaultOntrackGitHubClient.toMilestone(DefaultOntrackGitHubClient.java:122)
    at net.ontrack.extension.github.client.DefaultOntrackGitHubClient.getIssue(DefaultOntrackGitHubClient.java:56)
    at net.ontrack.extension.github.service.DefaultGitHubService$1.apply(DefaultGitHubService.java:67)
    at net.ontrack.extension.github.service.DefaultGitHubService$1.apply(DefaultGitHubService.java:64)
```

**Comment by dcoraboeuf** [comment]
#241 part of the change log, but has no milestone attached.
1. correcting the NPE
2. workaround by attaching a milestone (1.38)
