### ISSUE TITLE
If commit message contains multiple 'possible' issue ticket pattern, revision and information tabs from the changlog failed.

### ISSUE THREAD

**Issue by flesire** [dcoraboeuf/ontrack#253]
Extract for the log :

ERROR   28733428@qtp-32341043-3871      [39d277f4-8dd6-4817-aeea-b7b619a2dcf4] [ErrorCollection{status=404, errors={}, errorMessages=[Issue Does Not Exist]}] [net.ontrack.web.support.DefaultErrorHandler]

**Comment by dcoraboeuf** [comment]
Complete stack trace:

```
RestClientException{statusCode=Optional.of(404), errorCollections=[ErrorCollection{status=404, errors={}, errorMessages=[Issue Does Not Exist]}]}
        at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:47)
        at net.ontrack.extension.jira.service.DefaultJIRAService.getIssue(DefaultJIRAService.java:99)
        at net.ontrack.extension.svnexplorer.service.DefaultSVNExplorerService.getChangeLogIssue(DefaultSVNExplorerService.java:637)
        at net.ontrack.extension.svnexplorer.service.DefaultSVNExplorerService.collectIssuesForRevision(DefaultSVNExplorerService.java:621)
        at net.ontrack.extension.svnexplorer.service.DefaultSVNExplorerService.getChangeLogIssues(DefaultSVNExplorerService.java:203)
```

This happens when the message contains an issue that does not exist. Normally, the code at `net.ontrack.extension.jira.service.DefaultJIRAService#getIssue` should trap this exception and return a `null` issue, but this does not seem to happen.
